import crypto from "node:crypto";
import { Pool, type PoolClient, type QueryResultRow } from "pg";

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl || /^(file:|sqlite:)/i.test(databaseUrl)) throw new Error("DATABASE_URL must be a PostgreSQL connection string.");
const globalForDb = globalThis as unknown as { beforestPool?: Pool; beforestReady?: Promise<void> };
export const pool = globalForDb.beforestPool ?? new Pool({ connectionString: databaseUrl, max: 10 });
globalForDb.beforestPool = pool;

const teamSeed = [
  ["Business Intelligence", "business-intelligence"], ["Content & Storytelling", "content-storytelling"],
  ["Collective Design & Support", "collective-design-support"], ["Community Engagement", "community-engagement"],
  ["Regolith", "regolith"], ["Legal & Liaisoning", "legal-liaisoning"], ["HR", "hr"],
  ["Finance & Accounts", "finance-accounts"], ["Collective Operations", "collective-operations"], ["Bewild", "bewild"],
] as const;

async function initializeReferenceData() {
  await pool.query("SELECT 1 FROM projects LIMIT 1");
  for (const [name, collectionKey] of teamSeed) await pool.query("INSERT INTO notification_teams (name, collection_key) VALUES ($1, $2) ON CONFLICT DO NOTHING", [name, collectionKey]);
  await pool.query("INSERT INTO projects (name, description) VALUES ($1, $2) ON CONFLICT DO NOTHING", ["Beforest knowledge", "Shared Beforest knowledge base"]);
}
function ready() { globalForDb.beforestReady ??= initializeReferenceData(); return globalForDb.beforestReady; }
async function query<T extends QueryResultRow = QueryResultRow>(text: string, values: unknown[] = []) { await ready(); return (await pool.query<T>(text, values)).rows; }
async function tx<T>(work: (client: PoolClient) => Promise<T>) { await ready(); const client = await pool.connect(); try { await client.query("BEGIN"); const result = await work(client); await client.query("COMMIT"); return result; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }

export type AppRole = "Admin" | "User";
export type AppUser = { id: number; name: string; email: string; role: AppRole; teamId?: number | null; active: boolean; mustChangePassword: boolean; lastActiveAt?: string | null; createdAt: string };
export type NotificationTeam = { id: number; name: string; collectionKey: string; active: boolean; createdAt: string };
export type ChatMessage = { role: "user" | "assistant"; content: string };
export type RetrievalTrace = { documentId?: string | null; fileId?: string | null; filename?: string | null; retrievedText?: string | null; retrievalScore?: number | null; citation?: string | null };
export type KnowledgeProject = { id: number; name: string; description: string; createdBy: string; createdAt: string; threadCount: number };

function hashPassword(password: string, salt = crypto.randomBytes(16).toString("hex")) { return `${salt}:${crypto.pbkdf2Sync(password, salt, 210000, 32, "sha256").toString("hex")}`; }
function verifyPassword(password: string, stored: string) { const [salt, hash] = stored.split(":"); if (!salt || !hash) return false; const candidate = hashPassword(password, salt).split(":")[1]; return crypto.timingSafeEqual(Buffer.from(candidate, "hex"), Buffer.from(hash, "hex")); }
function hashToken(token: string) { return crypto.createHash("sha256").update(token).digest("hex"); }
function mapUser(row: Record<string, unknown>): AppUser { return { id: Number(row.id), name: String(row.name), email: String(row.email), role: row.role === "Admin" ? "Admin" : "User", teamId: row.teamId == null ? null : Number(row.teamId), active: Boolean(row.active), mustChangePassword: Boolean(row.mustChangePassword ?? row.must_change_password), lastActiveAt: row.lastActiveAt == null ? null : String(row.lastActiveAt), createdAt: String(row.createdAt ?? row.created_at) }; }
const userSelect = `SELECT u.id, u.name, u.email, u.role, u.active, u.must_change_password AS "mustChangePassword", u.last_active_at AS "lastActiveAt", u.created_at AS "createdAt", (SELECT team_id FROM notification_team_members WHERE user_id = u.id AND active = TRUE LIMIT 1) AS "teamId" FROM app_users u`;

export async function ensureDefaultAdmin() { const [{ count }] = await query<{ count: string }>("SELECT COUNT(*)::text AS count FROM app_users"); if (Number(count) > 0) return; if (!process.env.DEFAULT_ADMIN_EMAIL || !process.env.DEFAULT_ADMIN_PASSWORD) throw new Error("DEFAULT_ADMIN_EMAIL and DEFAULT_ADMIN_PASSWORD are required to seed the first admin user."); await createUser({ name: process.env.DEFAULT_ADMIN_NAME || "Seshu", email: process.env.DEFAULT_ADMIN_EMAIL, password: process.env.DEFAULT_ADMIN_PASSWORD, role: "Admin", active: true }); }
export async function listUsers() { await ensureDefaultAdmin(); return (await query<Record<string, unknown>>(`${userSelect} ORDER BY u.id`)).map(mapUser); }
export async function listNotificationTeams() { return query<NotificationTeam>(`SELECT id, name, collection_key AS "collectionKey", active, created_at AS "createdAt" FROM notification_teams WHERE active = TRUE ORDER BY name`); }
export async function notificationTeamExists(teamId: number) { return (await query("SELECT id FROM notification_teams WHERE id = $1 AND active = TRUE", [teamId])).length > 0; }
export async function assignUserToTeam(userId: number, teamId: number) { if (!(await notificationTeamExists(teamId))) return false; await tx(async (client) => { await client.query("UPDATE notification_team_members SET active = FALSE WHERE user_id = $1", [userId]); await client.query("INSERT INTO notification_team_members (team_id, user_id, active) VALUES ($1, $2, TRUE) ON CONFLICT (team_id, user_id) DO UPDATE SET active = TRUE", [teamId, userId]); }); return true; }
export async function getNotificationTeamByCollectionKey(collectionKey: string) { return (await query("SELECT id, name, collection_key AS \"collectionKey\" FROM notification_teams WHERE collection_key = $1 AND active = TRUE", [collectionKey]))[0] as { id: number; name: string; collectionKey: string } | undefined; }
export async function getNotificationTeam(teamId: number) { return (await query("SELECT id, name, collection_key AS \"collectionKey\" FROM notification_teams WHERE id = $1 AND active = TRUE", [teamId]))[0] as { id: number; name: string; collectionKey: string } | undefined; }

export async function createUser(user: { name: string; email: string; password: string; role: AppRole; active?: boolean; mustChangePassword?: boolean }) {
  const inserted = (await query<{ id: number }>(
    "INSERT INTO app_users (name, email, password_hash, role, active, must_change_password) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id",
    [user.name, user.email.toLowerCase(), hashPassword(user.password), user.role, user.active !== false, user.mustChangePassword === true],
  ))[0];
  const row = (await query<Record<string, unknown>>(`${userSelect} WHERE u.id = $1`, [inserted.id]))[0];
  return mapUser(row);
}
export async function updateUser(id: number, updates: Partial<{ name: string; email: string; password: string; role: AppRole; active: boolean; mustChangePassword: boolean }>) { if (!(await query("SELECT id FROM app_users WHERE id = $1", [id])).length) return null; await tx(async (client) => { const fields: string[] = []; const values: unknown[] = []; const set = (field: string, value: unknown) => { fields.push(`${field} = $${values.length + 1}`); values.push(value); }; if (updates.name !== undefined) set("name", updates.name); if (updates.email !== undefined) set("email", updates.email.toLowerCase()); if (updates.password !== undefined) set("password_hash", hashPassword(updates.password)); if (updates.role !== undefined) set("role", updates.role); if (updates.active !== undefined) set("active", updates.active); if (updates.mustChangePassword !== undefined) set("must_change_password", updates.mustChangePassword); if (fields.length) { values.push(id); await client.query(`UPDATE app_users SET ${fields.join(", ")} WHERE id = $${values.length}`, values); } if (updates.active === false) await client.query("DELETE FROM auth_sessions WHERE user_id = $1", [id]); }); return mapUser((await query<Record<string, unknown>>(`${userSelect} WHERE u.id = $1`, [id]))[0]); }
export async function deleteUser(id: number) { const result = await query("DELETE FROM app_users WHERE id = $1 RETURNING id", [id]); return result.length > 0; }
export async function loginUser(email: string, password: string) { await ensureDefaultAdmin(); const row = (await query<Record<string, unknown> & { passwordHash: string }>("SELECT id, name, email, password_hash AS \"passwordHash\", role, active, must_change_password AS \"mustChangePassword\", last_active_at AS \"lastActiveAt\", created_at AS \"createdAt\" FROM app_users WHERE lower(email) = lower($1)", [email]))[0]; if (!row || !verifyPassword(password, row.passwordHash)) return { error: "Invalid email or password." }; if (!row.active) return { error: "Your account is inactive. Please contact admin." }; const token = crypto.randomBytes(32).toString("base64url"); await query("INSERT INTO auth_sessions (user_id, token_hash, expires_at) VALUES ($1, $2, $3)", [row.id, hashToken(token), new Date(Date.now() + 1209600000)]); await query("UPDATE app_users SET last_active_at = NOW() WHERE id = $1", [row.id]); return { token, user: mapUser({ ...row, lastActiveAt: new Date().toISOString() }) }; }
export async function getUserBySessionToken(token?: string | null) { await ensureDefaultAdmin(); if (!token) return null; const row = (await query<Record<string, unknown>>(`${userSelect} JOIN auth_sessions s ON s.user_id = u.id WHERE s.token_hash = $1 AND s.expires_at > NOW()`, [hashToken(token)]))[0]; if (!row || !row.active) return null; await query("UPDATE app_users SET last_active_at = NOW() WHERE id = $1", [row.id]); return mapUser(row); }
export async function countRecentlyActiveUsers(windowMinutes = 30) { const [{ count }] = await query<{ count: string }>("SELECT COUNT(*)::text AS count FROM app_users WHERE active = TRUE AND last_active_at IS NOT NULL AND last_active_at >= NOW() - ($1 * INTERVAL '1 minute')", [windowMinutes]); return Number(count); }
export async function logoutSession(token?: string | null) { if (token) await query("DELETE FROM auth_sessions WHERE token_hash = $1", [hashToken(token)]); }

export async function prepareDocumentNotificationDeliveries(input: { documentKey: string; documentVersion: number; teamId: number }) { return tx(async (client) => { const recipients = (await client.query<{ userId: number; name: string; email: string; status?: string }>(`SELECT u.id AS "userId", u.name, u.email, d.status FROM notification_team_members m JOIN app_users u ON u.id = m.user_id LEFT JOIN document_notification_deliveries d ON d.document_key = $1 AND d.document_version = $2 AND d.team_id = m.team_id AND d.user_id = u.id WHERE m.team_id = $3 AND m.active = TRUE AND u.active = TRUE ORDER BY u.id`, [input.documentKey, input.documentVersion, input.teamId])).rows; const result = []; for (const recipient of recipients) { await client.query("INSERT INTO document_notification_deliveries (document_key, document_version, team_id, user_id, status) VALUES ($1, $2, $3, $4, 'pending') ON CONFLICT DO NOTHING", [input.documentKey, input.documentVersion, input.teamId, recipient.userId]); const delivery = (await client.query<{ id: number }>("SELECT id FROM document_notification_deliveries WHERE document_key = $1 AND document_version = $2 AND team_id = $3 AND user_id = $4", [input.documentKey, input.documentVersion, input.teamId, recipient.userId])).rows[0]; result.push({ ...recipient, deliveryId: Number(delivery.id) }); } return result; }); }
export async function markDocumentNotificationDelivery(id: number, status: "sent" | "failed", errorMessage?: string) { await query("UPDATE document_notification_deliveries SET status = $1, sent_at = CASE WHEN $1 = 'sent' THEN NOW() ELSE sent_at END, error_message = $2, updated_at = NOW() WHERE id = $3", [status, errorMessage || null, id]); }

export async function listSessions(projectId: number | null | undefined, userEmail: string) { const conditions = ["s.user_email IS NOT NULL", "lower(s.user_email) = lower($1)"]; const values: unknown[] = [userEmail]; if (projectId === null) conditions.push("s.project_id IS NULL"); else if (projectId !== undefined) { values.push(projectId); conditions.push(`s.project_id = $${values.length}`); } const rows = await query<Record<string, unknown>>(`SELECT s.id, s.title, s.user_name AS "userName", s.user_email AS "userEmail", s.project_id AS "projectId", s.created_at AS "createdAt", s.updated_at AS "updatedAt", (SELECT content FROM chat_messages m WHERE m.session_id = s.id ORDER BY m.id LIMIT 1) AS "firstMessage" FROM chat_sessions s WHERE ${conditions.join(" AND ")} ORDER BY s.updated_at DESC LIMIT 100`, values); const seen = new Set<string>(); return rows.filter((row) => { const key = String(row.firstMessage || row.title); if (seen.has(key)) return false; seen.add(key); return true; }).map(({ firstMessage, ...row }) => ({ ...row, title: firstMessage || row.title })); }
export async function getSession(id: string, userEmail: string) { const session = (await query<Record<string, unknown>>("SELECT s.id, s.title, s.user_name AS \"userName\", s.user_email AS \"userEmail\", s.project_id AS \"projectId\", s.created_at AS \"createdAt\", s.updated_at AS \"updatedAt\" FROM chat_sessions s WHERE s.id = $1 AND lower(s.user_email) = lower($2)", [id, userEmail]))[0]; if (!session) return null; const messages = await query<{ role: string; content: string; metadata: unknown; createdAt: string }>("SELECT role, content, metadata, created_at AS \"createdAt\" FROM chat_messages WHERE session_id = $1 ORDER BY id", [id]); return { ...session, messages: messages.map((message) => ({ ...message, citations: message.metadata && typeof message.metadata === "object" && !Array.isArray(message.metadata) ? (message.metadata as { citations?: unknown[] }).citations || [] : [] })) }; }
export async function getSessionByTitle(title: string, projectId: number | null | undefined, userEmail: string) { const conditions = ["lower(s.user_email) = lower($1)", "(s.title = $2 OR EXISTS (SELECT 1 FROM chat_messages m WHERE m.session_id = s.id AND m.role = 'user' AND m.content = $2))"]; const values: unknown[] = [userEmail, title]; if (projectId === null) conditions.push("s.project_id IS NULL"); else if (projectId !== undefined) { values.push(projectId); conditions.push(`s.project_id = $${values.length}`); } const row = (await query<{ id: string }>(`SELECT s.id FROM chat_sessions s WHERE ${conditions.join(" AND ")} ORDER BY s.updated_at DESC LIMIT 1`, values))[0]; return row ? getSession(row.id, userEmail) : null; }
export async function saveConversation(id: string, title: string, messages: Array<ChatMessage & { citations?: unknown[] }>, projectId?: number | null, userName = "Seshu", userEmail?: string) { await tx(async (client) => { await client.query("INSERT INTO chat_sessions (id, title, user_name, user_email, project_id) VALUES ($1, $2, $3, $4, $5) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, user_name = EXCLUDED.user_name, user_email = EXCLUDED.user_email, project_id = EXCLUDED.project_id, updated_at = NOW()", [id, title, userName, userEmail?.toLowerCase() || null, projectId ?? null]); await client.query("DELETE FROM chat_messages WHERE session_id = $1", [id]); for (const message of messages) await client.query("INSERT INTO chat_messages (session_id, role, content, metadata) VALUES ($1, $2, $3, $4)", [id, message.role, message.content, JSON.stringify({ citations: message.citations || [] })]); }); }

export async function saveFeedback(sessionId: string, rating: "up" | "down" | "neutral", reason: "slow_response" | "wrong_citation" | "poor_retrieval" | "not_relevant" | "missing_incomplete_information" | "accurate_helpful" | "clear_easy_to_understand" | "relevant_complete" | "other", note?: string) { await query("INSERT INTO message_feedback (session_id, rating, reason, note) VALUES ($1, $2, $3, $4)", [sessionId, rating, reason, note?.trim() || null]); }
export async function listFeedback() { return query("SELECT f.id, f.session_id AS \"sessionId\", f.rating, f.reason, f.note, f.status, f.resolved_at AS \"resolvedAt\", f.resolution_note AS \"resolutionNote\", f.created_at AS \"createdAt\", COALESCE(s.user_name, 'Unknown user') AS \"userName\", (SELECT query FROM query_events q WHERE q.session_id = f.session_id ORDER BY q.id DESC LIMIT 1) AS query, EXISTS (SELECT 1 FROM in_app_notifications n WHERE n.feedback_id = f.id) AS \"notificationSent\" FROM message_feedback f LEFT JOIN chat_sessions s ON s.id = f.session_id ORDER BY f.id DESC LIMIT 100"); }
export async function resolveFeedback(feedbackId: number, resolutionNote?: string) { return tx(async (client) => { const result = { resolved: false, notified: false }; const feedback = (await client.query<Record<string, unknown>>("SELECT f.id, s.user_email AS \"userEmail\", s.user_name AS \"userName\" FROM message_feedback f LEFT JOIN chat_sessions s ON s.id = f.session_id WHERE f.id = $1", [feedbackId])).rows[0]; if (!feedback) return result; await client.query("UPDATE message_feedback SET status = 'resolved', resolved_at = NOW(), resolution_note = $1 WHERE id = $2", [resolutionNote?.trim() || null, feedbackId]); const recipient = feedback.userEmail ? (await client.query<{ id: number }>("SELECT id FROM app_users WHERE lower(email) = lower($1) AND active = TRUE", [feedback.userEmail])).rows[0] : feedback.userName ? (await client.query<{ id: number }>("SELECT id FROM app_users WHERE lower(name) = lower($1) AND active = TRUE ORDER BY id LIMIT 1", [feedback.userName])).rows[0] : undefined; if (recipient) { await client.query("INSERT INTO in_app_notifications (user_id, feedback_id, title, detail) VALUES ($1, $2, $3, $4) ON CONFLICT DO NOTHING", [recipient.id, feedbackId, "Feedback resolved", "Your feedback is resolved."]); result.notified = true; } result.resolved = true; return result; }); }
export async function listInAppNotifications(userId: number) { return query("SELECT id, feedback_id AS \"feedbackId\", title, detail, read_at AS \"readAt\", created_at AS \"createdAt\" FROM in_app_notifications WHERE user_id = $1 ORDER BY id DESC LIMIT 25", [userId]); }

export async function saveQueryEvent(event: { sessionId: string; userName?: string; query: string; model?: string; latencyMs?: number; chunks?: number; topScore?: number | null; sources?: string[]; responseId?: string | null; filterUsed?: unknown; maxNumResults?: number; traces?: RetrievalTrace[] }) { return tx(async (client) => { const row = (await client.query<{ id: number }>("INSERT INTO query_events (session_id, user_name, query, model, latency_ms, chunks, top_score, sources, response_id, filter_used, max_num_results) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id", [event.sessionId, event.userName || null, event.query, event.model || null, event.latencyMs || null, event.chunks || 0, event.topScore ?? null, JSON.stringify(event.sources || []), event.responseId || null, event.filterUsed ? JSON.stringify(event.filterUsed) : null, event.maxNumResults || null])).rows[0]; for (const trace of event.traces || []) await client.query("INSERT INTO retrieval_traces (query_event_id, document_id, file_id, filename, retrieved_text, retrieval_score, citation) VALUES ($1,$2,$3,$4,$5,$6,$7)", [row.id, trace.documentId || null, trace.fileId || null, trace.filename || null, trace.retrievedText || null, trace.retrievalScore ?? null, trace.citation || trace.filename || null]); return Number(row.id); }); }
export async function getQueryStats() { const rows = await query<Record<string, unknown>>("SELECT q.id, COALESCE(q.user_name, s.user_name, 'Unknown user') AS \"userName\", q.query, q.model, q.latency_ms AS \"latencyMs\", q.chunks, q.top_score AS \"topScore\", q.sources, q.response_id AS \"responseId\", q.filter_used AS \"filterUsed\", q.max_num_results AS \"maxNumResults\", q.created_at AS \"createdAt\", (SELECT rating FROM message_feedback f WHERE f.session_id = q.session_id ORDER BY f.id DESC LIMIT 1) AS feedback, r.expected_source AS \"expectedSource\", r.verdict, r.notes, rr.resolution, rr.notes AS \"resolutionNotes\", rr.closed_at AS \"closedAt\" FROM query_events q LEFT JOIN chat_sessions s ON s.id = q.session_id LEFT JOIN retrieval_reviews r ON r.query_event_id = q.id LEFT JOIN retrieval_resolutions rr ON rr.query_event_id = q.id ORDER BY q.id DESC LIMIT 100"); const traceRows = await query<Record<string, unknown>>("SELECT query_event_id AS \"queryEventId\", document_id AS \"documentId\", file_id AS \"fileId\", filename, retrieved_text AS \"retrievedText\", retrieval_score AS \"retrievalScore\", citation FROM retrieval_traces ORDER BY id"); const traces = traceRows.reduce<Record<number, Array<Record<string, unknown>>>>((result, row) => { const id = Number(row.queryEventId); (result[id] ||= []).push(row); return result; }, {}); const average = (await query<{ average: string | null }>("SELECT AVG(latency_ms)::text AS average FROM query_events WHERE latency_ms IS NOT NULL"))[0]?.average; return { rows: rows.map((row) => ({ ...row, sources: row.sources || [], filterUsed: row.filterUsed || null, traces: traces[Number(row.id)] || [] })), averageLatencyMs: average ? Math.round(Number(average)) : null }; }
export async function saveRetrievalReview(review: { queryEventId: number; expectedSource?: string; verdict: "relevant" | "miss"; notes?: string }) { await query("INSERT INTO retrieval_reviews (query_event_id, expected_source, verdict, notes) VALUES ($1,$2,$3,$4) ON CONFLICT (query_event_id) DO UPDATE SET expected_source=EXCLUDED.expected_source, verdict=EXCLUDED.verdict, notes=EXCLUDED.notes, reviewed_at=NOW()", [review.queryEventId, review.expectedSource || null, review.verdict, review.notes || null]); }
export async function saveRetrievalResolution(resolution: { queryEventId: number; resolution: string; notes?: string }) { await query("INSERT INTO retrieval_resolutions (query_event_id, resolution, notes) VALUES ($1,$2,$3) ON CONFLICT (query_event_id) DO UPDATE SET resolution=EXCLUDED.resolution, notes=EXCLUDED.notes, closed_at=NOW()", [resolution.queryEventId, resolution.resolution, resolution.notes || null]); }
export async function getActiveModelConfig() { return (await query("SELECT id, generation_model AS \"generationModel\", embedding_model AS \"embeddingModel\", system_prompt AS \"systemPrompt\", active, created_at AS \"createdAt\" FROM model_configs ORDER BY active DESC, id DESC LIMIT 1"))[0]; }
export async function saveModelConfig(config: { generationModel: string; embeddingModel: string; systemPrompt: string; active?: boolean }) { await tx(async (client) => { if (config.active) await client.query("UPDATE model_configs SET active=FALSE"); await client.query("INSERT INTO model_configs (generation_model, embedding_model, system_prompt, active) VALUES ($1,$2,$3,$4)", [config.generationModel, config.embeddingModel, config.systemPrompt, config.active === true]); }); }
export async function getSettings() { return query<{ key: string; value: string }>("SELECT key, value FROM system_settings"); }
export async function saveSetting(key: string, value: boolean) { await query("INSERT INTO system_settings (key,value) VALUES ($1,$2) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value, updated_at=NOW()", [key, value ? "true" : "false"]); }
export async function saveSettingValue(key: string, value: string) { await query("INSERT INTO system_settings (key,value) VALUES ($1,$2) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value, updated_at=NOW()", [key, value]); }
export async function getSettingValue(key: string, fallback = "") { return (await query<{ value: string }>("SELECT value FROM system_settings WHERE key=$1", [key]))[0]?.value ?? fallback; }
export async function getNumberSetting(key: string, fallback: number, options?: { min?: number; max?: number }) { const raw = Number(await getSettingValue(key, String(fallback))); const value = Number.isFinite(raw) ? raw : fallback; return Math.min(options?.max ?? value, Math.max(options?.min ?? value, value)); }

export async function createDocumentRecord(document: { id: string; name: string; mimeType?: string; sizeBytes?: number; departmentId?: string; folderId?: string; documentType?: string; accessGroup?: string; ownerName?: string; version?: number }) { await tx(async (client) => { await client.query("INSERT INTO documents (id,name,mime_type,size_bytes,department_id,folder_id,document_type,access_group,owner_name,version,status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'processing')", [document.id, document.name, document.mimeType || null, document.sizeBytes || null, document.departmentId || "general", document.folderId || "uploaded-documents", document.documentType || "document", document.accessGroup || "all", document.ownerName || "Unknown user", document.version || 1]); await client.query("INSERT INTO processing_jobs (document_id,type,status) VALUES ($1,'openai_vector_index','processing')", [document.id]); }); }
export async function updateDocumentRecord(id: string, updates: Partial<{ openaiFileId: string | null; vectorStoreFileId: string | null; status: string; error: string | null }>) { if (!(await query("SELECT id FROM documents WHERE id=$1", [id])).length) return null; await tx(async (client) => { if (updates.openaiFileId !== undefined) await client.query("UPDATE documents SET openai_file_id=$1,updated_at=NOW() WHERE id=$2", [updates.openaiFileId, id]); if (updates.vectorStoreFileId !== undefined) await client.query("UPDATE documents SET vector_store_file_id=$1,updated_at=NOW() WHERE id=$2", [updates.vectorStoreFileId, id]); if (updates.status !== undefined) { await client.query("UPDATE documents SET status=$1,updated_at=NOW() WHERE id=$2", [updates.status, id]); await client.query("UPDATE processing_jobs SET status=$1,updated_at=NOW() WHERE document_id=$2", [updates.status === "published" || updates.status === "ready" ? "completed" : updates.status, id]); } if (updates.error !== undefined) { await client.query("UPDATE documents SET error=$1,updated_at=NOW() WHERE id=$2", [updates.error, id]); if (updates.error) await client.query("UPDATE processing_jobs SET error=$1,status='failed',updated_at=NOW() WHERE document_id=$2", [updates.error, id]); } }); return (await query("SELECT * FROM documents WHERE id=$1", [id]))[0]; }
export async function softDeleteDocumentByFileId(fileId: string) { await query("UPDATE documents SET status='deleted',is_current=FALSE,updated_at=NOW() WHERE openai_file_id=$1 OR vector_store_file_id=$1", [fileId]); }
export async function getDocumentByFileId(fileId: string) { return (await query("SELECT id,name,mime_type AS \"mimeType\",size_bytes AS \"sizeBytes\",department_id AS \"departmentId\",folder_id AS \"folderId\",document_type AS \"documentType\",status,version,is_current AS \"isCurrent\",access_group AS \"accessGroup\",owner_name AS \"ownerName\" FROM documents WHERE openai_file_id=$1 OR vector_store_file_id=$1 ORDER BY updated_at DESC LIMIT 1", [fileId]))[0]; }
export async function listProjects() { return query<KnowledgeProject>("SELECT p.id,p.name,p.description,p.created_by AS \"createdBy\",p.created_at AS \"createdAt\",COUNT(s.id)::int AS \"threadCount\" FROM projects p LEFT JOIN chat_sessions s ON s.project_id=p.id GROUP BY p.id ORDER BY p.id"); }
export async function createProject(project: { name: string; description?: string; createdBy?: string }) { return (await query<KnowledgeProject>("INSERT INTO projects (name,description,created_by) VALUES ($1,$2,$3) RETURNING id,name,description,created_by AS \"createdBy\",created_at AS \"createdAt\",0 AS \"threadCount\"", [project.name, project.description || "", project.createdBy || "Seshu"]))[0]; }
export async function getAdminStats() { const [activeUsers, sessions, queries, positive, negative, documents, needsReview] = await Promise.all([countRecentlyActiveUsers(30), query<{ count: string }>("SELECT COUNT(*)::text AS count FROM chat_sessions"), query<{ count: string }>("SELECT COUNT(*)::text AS count FROM chat_messages WHERE role='user'"), query<{ count: string }>("SELECT COUNT(*)::text AS count FROM message_feedback WHERE rating='up'"), query<{ count: string }>("SELECT COUNT(*)::text AS count FROM message_feedback WHERE rating='down'"), query<{ count: string }>("SELECT COUNT(*)::text AS count FROM documents WHERE status!='deleted'"), query<{ count: string }>("SELECT COUNT(*)::text AS count FROM query_events q WHERE NOT EXISTS (SELECT 1 FROM retrieval_resolutions rr WHERE rr.query_event_id=q.id) AND (q.chunks=0 OR q.top_score IS NULL OR q.top_score<0.35 OR EXISTS (SELECT 1 FROM message_feedback f WHERE f.session_id=q.session_id AND f.rating='down'))")]); return { activeUsers, sessions: Number(sessions[0].count), queries: Number(queries[0].count), positive: Number(positive[0].count), negative: Number(negative[0].count), documents: Number(documents[0].count), needsReview: Number(needsReview[0].count) }; }
